development:
  adapter: postgresql
  database: growstuff_dev

test:
  adapter: postgresql
  database: growstuff_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  adapter: postgresql
  database: growstuff_prod
  pool: 5
  timeout: 5000
  username: growstuff
  host: localhost
  password: thisisnottherealpassword

staging:
  adapter: postgresql
  database: growstuff_prod
  pool: 5
  timeout: 5000
  username: growstuff
  host: localhost
  password: thisisnottherealpassword
